baseURL = 'https://gem.coop/'
languageCode = 'en-us'
title = 'gem.coop'
disableKinds = ['taxonomy', 'term']

[outputs]
  home = ['html', 'rss']
  section = ['html']

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[services]
  [services.rss]
    limit = 50

[caches]
  [caches.images]
    dir = ':cacheDir/images'
